### ISSUE TITLE
Doesn't work with windows 10?

### ISSUE THREAD

**Issue by alaskanloops** [jaredsohn/mutefm#6]
I am correct in assuming this doesn't work in Window's 10?

**Comment by jaredsohn** [comment]
No idea; I've never used Windows 10 (I run MacOS exclusively now.)

While developing this it would work for older style apps but not for what used to be called Metro apps.

**Comment by alaskanloops** [comment]
Cool man.  Yeah I'm mostly MacOS as well, but unfortunately Alaska is mostly .net/Microsoft products so for work I have to develop on Windows.

My search for a solution continues!

**Comment by jaredsohn** [comment]
If you're using what used to be called Metro apps, I think the operating system does something similar already. Otherwise if you spend a lot of your time in the browser, check out my MuteTab Chrome extension and turn on experimental music ducking. mutetab.com)

**Comment by alaskanloops** [comment]
Great, I'll check it out!  There used to be a firefox extension that did something similar.  It gets really annoying having to start music up every time I pause Pluralsight (or related) to write code.
